In [16]:
import pandas as pd
from openpyxl import load_workbook
#import class_annotation.ipynb

In [17]:
# Load the workbook
workbook = load_workbook('/Users/leonardhaas/code/streamlit/data/Zensus22_Sonderauswertung_Haas.xlsx', read_only=True)

# Get all sheet names
sheet_names = workbook.sheetnames

In [18]:
sheet_names

['Titel',
 'Impressum',
 'Erläuterungen zur Methodik',
 'ISCO Hauptgruppen (1-St.)',
 'ISCO Berufsgruppen (2-St.)',
 'ISCO Berufsuntergruppen (3-St.)',
 'ISCO Berufsgattungen (4-St.)']

In [19]:
haupt_gruppen_1 = pd.read_excel('/Users/leonardhaas/code/streamlit/data/Zensus22_Sonderauswertung_Haas.xlsx', sheet_name=sheet_names[3], header=3)  # Row 2 as header (index 1)
berufs_gruppen_2 = pd.read_excel('/Users/leonardhaas/code/streamlit/data/Zensus22_Sonderauswertung_Haas.xlsx', sheet_name=sheet_names[4], header=3)  # Row 2 as header (index 1)
berufs_unter_gruppen_3 = pd.read_excel('/Users/leonardhaas/code/streamlit/data/Zensus22_Sonderauswertung_Haas.xlsx', sheet_name=sheet_names[5], header=3)  # Row 2 as header (index 1)
berufs_gattungen_4 = pd.read_excel('/Users/leonardhaas/code/streamlit/data/Zensus22_Sonderauswertung_Haas.xlsx', sheet_name=sheet_names[6], header=3)  # Row 2 as header (index 1)

In [20]:
raw_data = pd.read_csv('/Users/leonardhaas/code/streamlit/data/statistischer-bericht-verdienste-5623601243225 3.csv',sep=';',header=2)

In [21]:
search_term = "Berufsgattungen"

start_row = raw_data[raw_data.apply(lambda row: row.astype(str).str.contains(search_term, case=False).any(), axis=1)].index

In [22]:
# Extract the section starting from "Berufsgattungen"
relevant_data = raw_data.iloc[start_row[0]:]

# Clean and restructure the data to extract required columns
# Dropping unnecessary columns and rows with excessive NaN values
cleaned_data = relevant_data.dropna(how='all', axis=1).reset_index(drop=True)
cleaned_data.columns = cleaned_data.iloc[0]  # Set the first row as column headers
cleaned_data = cleaned_data[1:].reset_index(drop=True)  # Remove the header row from the data


cleaned_data.columns = ['bezeichnung_kldb','median_brutto','average_brutto']
structured_data = cleaned_data
""""""
# Clean up numeric fields (removing spaces, handling non-numeric entries)
structured_data['median_brutto'] = structured_data['median_brutto'].str.replace(r'[^\d,]', '', regex=True).str.replace(',', '.').astype(float, errors='ignore')
structured_data['average_brutto'] = structured_data['average_brutto'].str.replace(r'[^\d,]', '', regex=True).str.replace(',', '.').astype(float, errors='ignore')

# Preview the final structured data

In [23]:

structured_data.dropna(subset=['bezeichnung_kldb'], inplace=True)
structured_data['code_kldb'] =structured_data['bezeichnung_kldb'].str.extract('(\d+)', expand=False)

In [24]:
structured_data['median_brutto'] = pd.to_numeric(structured_data['median_brutto'], errors='coerce').fillna(0).astype(int)

In [36]:
structured_data.to_csv('verdienst_destatis_kldb_5steller.csv')

In [26]:
raw_data

,Berufliche Tätigkeit (KldB 2010),Bruttomonatsverdienste (ohne Sonderzahlungen),Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63
0,NaN,insgesamt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Median,arithm.\nMittel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Euro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Berufshauptgruppen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1484,01104 Offiziere,5 330,5 564,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1485,01203 Unteroffiziere mit Portepee,3 785,3 815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1486,01302 Unteroffiziere ohne Portepee,3 029,3 089,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1487,01402 Angeh. reguläre Streitkräfte sonst.Ränge,2 627,2 704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1488,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
hauptgruppen_kldb=raw_data[5:41]

In [35]:
hauptgruppen_kldb.sort_values(by='Bruttomonatsverdienste (ohne Sonderzahlungen)',ascending=False)

,Berufliche Tätigkeit (KldB 2010),Bruttomonatsverdienste (ohne Sonderzahlungen),Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63
22,43 Informatik- und andere IKT-Berufe,5 477,5 816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,84 Lehrende und ausbildende Berufe,5 228,5 348,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,27 Techn.Entwickl.Konstr.Produktionssteuer.,5 077,5 494,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,"72 Finanzdienstl.Rechnungsw.,Steuerberatung",4 724,5 461,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,"61 Einkaufs-, Vertriebs- und Handelsberufe",4 716,5 412,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,"92 Werbung,Marketing,kaufm,red.Medienberufe",4 584,5 189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,"31 Bauplanung,Architektur,Vermessungsberufe",4 534,4 947,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,"71 Berufe Unternehmensführung,-organisation",4 454,5 544,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,"41 Mathematik-Biologie-Chemie-,Physikberufe",4 313,4 793,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,"94 Darstellende, unterhaltende Berufe",4 176,5 409,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,91 Geistes-Gesellschafts-Wirtschaftswissen.,4 158,4 822,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,"42 Geologie-,Geografie-,Umweltschutzberufe",4 153,4 720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,73 Berufe in Recht und Verwaltung,4 019,4 461,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,"53 Schutz-,Sicherheits-, Überwachungsberufe",3 859,4 010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,"26 Mechatronik-, Energie- u. Elektroberufe",3 815,4 232,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,81 Medizinische Gesundheitsberufe,3 751,4 643,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,25 Maschinen- und Fahrzeugtechnikberufe,3 720,4 061,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,"83 Erziehung,soz.,hauswirt.Berufe,Theologie",3 567,3 673,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,"24 Metallerzeugung,-bearbeitung, Metallbau",3 401,3 560,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,"23 Papier-,Druckberufe, tech.Mediengestalt.",3 270,3 542,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,34 Gebäude- u. versorgungstechnische Berufe,3 223,3 475,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,"82 Nichtmed.Gesundheit,Körperpfl.,Medizint.",3 201,3 373,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,"21 Rohstoffgewinn,Glas-,Keramikverarbeitung",3 181,3 512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,"93 Produktdesign, Kunsthandwerk",3 150,3 677,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,32 Hoch- und Tiefbauberufe,3 149,3 355,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,"51 Verkehr, Logistik (außer Fahrzeugführ.)",3 000,3 262,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,52 Führer von Fahrzeug- u. Transportgeräten,2 999,3 129,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,"22 Kunststoff- u. Holzherst.,-verarbeitung",2 943,3 125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,33 (Innen-)Ausbauberufe,2 941,3 050,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,62 Verkaufsberufe,2 845,3 342,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,28 Textil- und Lederberufe,2 740,3 020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,29 Lebensmittelherstellung u. -verarbeitung,2 724,2 933,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,"12 Gartenbauberufe, Floristik",2 672,2 833,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,"63 Tourismus-, Hotel- und Gaststättenberufe",2 634,2 892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,"11 Land-, Tier-, Forstwirtschaftsberufe",2 531,2 779,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,54 Reinigungsberufe,2 493,2 629,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN